name: demo
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.0
  get_it: ^5.0.6
  url_launcher: ^5.7.10
  dropdown_formfield: ^0.1.3
  dropdownfield: ^1.0.3
  flutter_range_slider: ^1.5.0
  carousel_slider: ^3.0.0
  flutter_swiper: ^1.1.6
  flutter_rating_bar: ^3.2.0+1
  expandable: ^4.1.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  