name: demo
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"



# dependency_overrides:
#   
#   
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 


 
  cupertino_icons: ^1.0.0
  get_it: ^5.0.6
  url_launcher: ^5.7.10
  dropdown_formfield: ^0.1.3
  dropdownfield: ^1.0.3
  flutter_range_slider: ^1.5.0
  carousel_slider: ^3.0.0
  flutter_swiper: ^1.1.6
  flutter_rating_bar: ^3.2.0+1
  expandable: ^4.1.3
  flutter_custom_clippers: ^1.1.2
  percent_indicator: ^2.1.9+1
  modal_bottom_sheet: ^1.0.0+1
  rflutter_alert: ^2.0.1
  provider: ^4.3.3
  google_maps_flutter: ^2.0.1
  datetime_picker_formfield: ^2.0.0
  flutter_open_whatsapp: ^0.1.2
  date_format: ^2.0.2
  flutter_animated_dialog: ^2.0.0
  intl: ^0.17.0-nullsafety.2
  image_picker: ^0.7.2+1
  image_picker_platform_interface: ^2.0.0 
  http_parser: ^4.0.0
  url_launcher_platform_interface: ^1.0.9
  plugin_platform_interface: ^1.0.1
  flutter_facebook_login: ^3.0.0
  flutter_facebook_auth: ^3.0.0
  firebase_core: 
  firebase_auth:
  http: ^0.13.0
  # form validator
  form_validator: ^0.1.7
  google_sign_in: "^4.5.1"
  # cloud_firestore: ^0.16.0+1-nullsafety.0
 
  

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  image_picker: ^0.7.2+1
  
  firebase_core: 
  firebase_auth:
  image_picker_platform_interface: ^2.0.1 
  # http: ^0.13.0
  http_parser: ^4.0.0
  url_launcher: ^5.7.10
  url_launcher_platform_interface: ^1.0.9
  plugin_platform_interface: ^1.0.1
 


   

 
  
 


 


dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter_application_id:
#   android: 
#     id: "com.sycryption.zerobrokerandroid"
#     name: "ZeroBroker - Android"
#   ios:
#     id: "com.sycryption.zeroBrokerIos"
#     name: "ZeroBroker - iOS"    


flutter:
  uses-material-design: true

  